### ISSUE TITLE
Create poetry plugin

### ISSUE THREAD

**Issue by branchvincent** [taskipy/taskipy#32]
Create a [Poetry plugin](https://github.com/python-poetry/poetry/blob/45a9b8f20384591d0a33ae876bcf23656f928ec0/docs/docs/plugins.md#plugins), which just [landed on master](https://github.com/python-poetry/poetry/pull/3733) and is expected to ship with [Poetry 1.2](https://github.com/python-poetry/poetry/issues/1856).

## Usage

The usage could look like either:

```console
poetry task lint
```

or

```console
poetry lint
```

**Comment by illBeRoy** [comment]
Back on the table since [plugins are now officially supported](https://python-poetry.org/docs/plugins)

**Comment by brunolnetto** [comment]
It seems a great opportunity for me to evoke my [n-cents-comment](https://github.com/python-poetry/poetry/issues/2496#issuecomment-1366140648): 

Question: why not `poetry alias`? 
Answer: Because decisions are made decentralized, and people like it that way. 

Question: Why should it be a poetry thing?
Answer: Because command `git` already has a command `aliases`, which suits well.

Question: Why will it not happen in a near future?
Answer: Because it is a one-person idea, and it seems a bit-pretentious solution from OP-me.

**Comment by eugenetriguba** [comment]
There is now a poetry plugin released for taskipy: https://github.com/taskipy/poetry-plugin-taskipy

You can install it from PyPI as `poetry-plugin-taskipy`. Closing this ticket out
