### ISSUE TITLE
Can the pin on mslex v0 be raised to v1?

### ISSUE THREAD

**Issue by Zeitsperre** [taskipy/taskipy#68]
By sheer coincidence, `mslex` is now available on conda-forge: https://github.com/conda-forge/mslex-feedstock

The minimum version of `mslex` available is v1.1.0, which is marked incompatible with `taskipy`:
```
taskipy 1.12.0 has requirement mslex<0.4.0,>=0.3.0; sys_platform == "win32", but you have mslex 1.1.0.
Tests failed for taskipy-1.12.0-py39h46a1287_1.conda - moving package to D:\bld\broken 
```

This error is coming from the pin here:
https://github.com/taskipy/taskipy/blob/51373e12ec47e96684d2bf2bb77fda52c0e91529/pyproject.toml#L29

My understanding of the "^X.Y.Z" notation was that all versions that begin with "X" would be valid, so the error is strange to begin with, but given that `mslex` seems to have recently jumped to v1.0 (https://github.com/smoofra/mslex/tags), perhaps it would be worthwhile to adapt to this version?

**Comment by eugenetriguba** [comment]
@Zeitsperre With semver, 0.Y.Z is considered "initial development". There are no stability guarantees between minor versions but generally patch versions should be stable.

https://semver.org/spec/v1.0.0.html
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

> perhaps it would be worthwhile to adapt to this version?

This is actually updated on the `2.0` branch, but we don't have any formal timelines for releasing that yet: https://github.com/taskipy/taskipy/blob/2.0/pyproject.toml#L26.

I took a look through the project changes though, and I don't see an issue with updating this dependency. The changes since then have been quite minor. I'll make a PR to update this and reach out to @illBeRoy to get that released. Thanks for mentioning it 👍

**Comment by eugenetriguba** [comment]
@illBeRoy Merged in, we'll just need a release created whenever you have a moment 🙂
